slam_toolbox:
  ros__parameters:
    use_sim_time: true
    slam_toolbox: true

    mode: "mapping"
    map_update_interval: 5.0
    resolution: 0.03
    max_laser_range: 10.0
    minimum_time_interval: 0.5
    
    base_frame: base_link

    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.1
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_resposnse_coarse: 0.35
    loop_match_minimum_resposnse_fine: 0.45

    optimization_max_iteration: 20
    use_scan_matching: true
    use_loop_closing: true
    
