<?xml version="1.0"?>
<robot name="simple_bot" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find simplebot_description)/urdf/material.xacro"/>
    <xacro:include filename="$(find simplebot_description)/urdf/gazebo.xacro"/>


    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_width" value="0.04" />
    <xacro:property name="castor_radius" value="0.07" />

    <xacro:property name="box_width" value="0.3" />
    <xacro:property name="box_length" value="0.5" />
    <xacro:property name="box_height" value="0.075" />

    <xacro:property name="z_off" value="0.12" />

    <xacro:property name="lidar_height" value="0.1" />
    <xacro:property name="imu_side" value="0.05" />
    
    <link name="base_footprint"/>
    
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
        
    </link>

    <joint name="base_joint" type="fixed">
        <origin xyz="0.0 0.0 ${z_off}" rpy="0.0 0.0 0.0"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>

    <xacro:macro name="wheel_def" params="wheel_name direction">
        <link name="${wheel_name}_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="gray"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="1.0"/>
                <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0.0" ixz="0.0" iyz="0.0"/>
            </inertial>
        </link>

        <joint name="${wheel_name}_joint" type="continuous">
            <origin xyz="-${box_length/4} ${direction * (box_width/2 + wheel_width/2)} -${(z_off - wheel_radius)}" rpy="0.0 0.0 0.0"/>
            <parent link="base_link"/>
            <child link="${wheel_name}_link"/>
            <axis xyz="0.0 1.0 0.0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel_def wheel_name="right_wheel" direction="-1"/>
    <xacro:wheel_def wheel_name="left_wheel" direction="1"/>

    <link name="castor_wheel">
        <visual>
            <geometry>
                <sphere radius="${castor_radius}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${castor_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="caster_joint" type="fixed">
        <origin xyz="${box_length/3} 0.0 -${z_off - castor_radius}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="castor_wheel"/>
    </joint>

    <link name="lidar_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.05" length="${lidar_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.05" length="${lidar_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.001"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="lidar_joint" type="fixed">
        <origin xyz="${box_length/3} 0.0 ${(lidar_height/2 + box_height/2)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="lidar_link"/>
    </joint>

    <link name="imu_link">
        <visual>
            <geometry>
                <box size="${imu_side} ${imu_side} ${imu_side}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${imu_side} ${imu_side} ${imu_side}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.0005"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="imu_joint" type="fixed">
        <origin xyz="0.0 0.0 0.04" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>


</robot>